services:
    _defaults:
        public: true

    App\Command\Handler\ReadArticle:
        arguments:
            - '@App\Repository\ArticleRepository'

    App\Command\Handler\ListArticles:
        arguments:
            - '@App\Repository\ArticleRepository'

    App\Command\Handler\CreateArticle:
        arguments:
            - '@doctrine.orm.entity_manager'
