services:
    App\Application\Controller\ArticleController:
        arguments:
            - '@App\Domain\Command\Bus\SimpleBus'
            - '@Symfony\Component\Form\FormFactoryInterface'
        tags:
            - 'controller.service_arguments'
