services:
    App\Application\Controller\ArticleController:
        arguments:
            - '@App\Command\Bus\SimpleBus'
            - '@form.factory'
        tags:
            - 'controller.service_arguments'
