security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_user_provider:
            id: App\Application\Security\UserProvider

    firewalls:
        main:
            stateless: true
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Application\Security\TokenAuthenticator

    access_control:
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: '^/', roles: ROLE_ADMIN, methods: [POST] }
