version: '3.7'

services:
  api_mysql:
    build:
      context: ./
      dockerfile: .docker/mysql/Dockerfile
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  api_nginx:
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    restart: on-failure
    ports:
      - '8081:80'
    depends_on:
      - api_php

  api_php:
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
      target: php
    restart: on-failure
    volumes:
      - './:/app'
    env_file:
      - .env
    user: 1000:1000
