list_articles:
    path: /articles
    methods: [GET]
    controller: App\Application\Controller\ArticleController::list

read_article:
    path: /articles/{slug}
    methods: [GET]
    controller: App\Application\Controller\ArticleController::read
    requirements:
        slug: '[a-z\-]+'

create_article:
    path: /articles
    methods: [POST]
    controller: App\Application\Controller\ArticleController::create
