list_articles:
    path: /articles
    methods: [GET]
    controller: App\Application\Controller\ArticleController::list

read_article:
    path: /articles/{slug}
    methods: [GET]
    controller: App\Application\Controller\ArticleController::read
    requirements:
        slug: '[a-z0-9\-]+'

create_article:
    path: /articles
    methods: [POST]
    controller: App\Application\Controller\ArticleController::create

publish_article:
    path: /articles/{id}/publish
    methods: [PATCH]
    controller: App\Application\Controller\ArticleController::publish
    requirements:
        id: '[\d]+'
