get_blog_posts:
    path: /blog/posts
    controller: App\Controller\PostController::getBlogPosts
    requirements:
        method: GET

get_blog_post:
    path: /blog/posts/{seoTitle}
    controller: App\Controller\PostController::getBlogPost
    requirements:
        method: GET
        seoTitle: '[a-z\-]+'

test:
  path: /test
  controller: App\Controller\PostController::test
