list_articles:
    path: /articles
    controller: App\Controller\ArticleController::list
    requirements:
        method: GET

read_article:
    path: /articles/{slug}
    controller: App\Controller\ArticleController::read
    requirements:
        method: GET
        slug: '[a-z\-]+'
