imports:
    - { resource: services/ }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Application,Command,Controller,EventListener,Entity,Migrations,Tests,Kernel.php}'

